alias reload!='. ~/.zshrc'
alias slime='open -a "/Applications/Sublime Text 2.app"'
alias be='bundle exec'
alias heroku='/usr/local/bin/heroku'
alias kcu='knife cookbook upload'
alias krff='knife role from file'
alias pf='/Users/edennis/Code/sge/platform/platform_harness/bin/platform'
